### ISSUE TITLE
Report viewer installation on 2012R2 requires NET-Framework-Core

### ISSUE THREAD

**Issue by VladyslavMatus** [criteo-cookbooks/wsus-server#10]
Installation of Report Viewer requires additional feature installation NET-Framework-Core (and it requires files from installation media (\sources\sxs) = you have to specify the source)

**Comment by Annih** [comment]
Hello @Vladyslav-M 

Thanks for this issue, we have already spotted that we are currently unable to setup properly report viewer on 2012R2 and we have plan to handle it soon.

Feel free to provide a PR if you are faster than us :)

Regards,

Annih

**Comment by Annih** [comment]
Support has been added a while ago.
