### ISSUE TITLE
Improper PowerShell Path?

### ISSUE THREAD

**Issue by jdgoins** [criteo-cookbooks/wsus-server#18]
Commit 9c6effa broke the path to PowerShell for 64 bit systems.

libraries/base_provider.rb, line 68

`interpreter = '%windir%/SysNative/WindowsPowershell/v1.0/PowerShell.exe'`

Should be 
`interpreter = '%windir%/SysWOW64/WindowsPowershell/v1.0/PowerShell.exe'`

Error:
`Generated at 2016-05-04 18:44:15 -0600
Mixlib::ShellOut::ShellCommandFailed: wsus_server_configuration[Wsus server configuration] (wsus-server::configure line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of %windir%/SysNative/WindowsPowershell/v1.0/PowerShell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -InputFormat None -EncodedCommand IAAgACAAIAAkAGEAcwBzAGUAbQBiAGwAeQAgAD0AIABbAFIAZQBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZABXAGkAdABoAFAAYQByAHQAaQBhAGwATgBhAG0AZQAoACcATQBpAGMAcgBvAHMAbwBmAHQALgBVAHAAZABhAHQAZQBTAGUAcgB2AGkAYwBlAHMALgBBAGQAbQBpAG4AaQBzAHQAcgBhAHQAaQBvAG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAYQBzAHMAZQBtAGIAbAB5ACAALQBuAGUAIAAkAG4AdQBsAGwAKQAgAHsACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGIAdQBmAGYAZQByACAAcwBpAHoAZQAgAHQAbwAgAGEAdgBvAGkAZAAgADgAMAAgAGMAbwBsAHUAbQBuACAAbABpAG0AaQB0AGEAdABpAG8AbgAsACAAYQAgAHcAaQBkAHQAaAAgAGcAcgBlAGEAdABlAHIAIAB0AGgAYQBuACAAMQAwADAAMAAgAGkAcwAgAHUAcwBlAGwAZQBzAHMACgAgACAAIAAgACAAIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBCAHUAZgBmAGUAcgBTAGkAegBlACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEgAbwBzAHQALgBTAGkAegBlACgAMQAwADAAMAAsACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AQgB1AGYAZgBlAHIAUwBpAHoAZQAuAEgAZQBpAGcAaAB0ACkACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGkAbgB2AGEAcgBpAGEAbgB0ACAAYwB1AGwAdAB1AHIAZQAgAGYAbwByACAAYwB1AHIAcgBlAG4AdAAgAHMAZQBzAHMAaQBvAG4AIAB0AG8AIABhAHYAbwBpAGQAIABGAGwAbwBhAHQAaQBuAGcAIABwAG8AaQBuAHQAIABjAG8AbgB2AGUAcgBzAGkAbwBuACAAaQBzAHMAdQBlAAoAIAAgACAAIAAgACAAWwBUAGgAcgBlAGEAZABpAG4AZwAuAFQAaAByAGUAYQBkAF0AOgA6AEMAdQByAHIAZQBuAHQAVABoAHIAZQBhAGQALgBDAHUAcgByAGUAbgB0AEMAdQBsAHQAdQByAGUAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEcAbABvAGIAYQBsAGkAegBhAHQAaQBvAG4ALgBDAHUAbAB0AHUAcgBlAEkAbgBmAG8AXQA6ADoASQBuAHYAYQByAGkAYQBuAHQAQwB1AGwAdAB1AHIAZQAKAAoAIAAgACAAIAAgACAAIwAgAEQAZQBmAGkAbgBlAHMAIABzAGkAbgBnAGwAZQAtAGwAZQB2AGUAbAAgACIAWQBBAE0ATAAiACAAZgBvAHIAbQBhAHQAdABlAHIAcwAgAHQAbwAgAGEAdgBvAGkAZAAgAEQAYQB0AGUAVABpAG0AZQAgAGEAbgBkACAAVABpAG0AZQBTAHAAYQBuACAAYwBvAG4AdgBlAHIAcwBpAG8AbgAgAGkAcwBzAHUAZQAgAGkAbgAgAHIAdQBiAHkACgAgACAAIAAgACAAIAAkAHYAYQBsAHUAZQBGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgAGkAZgAgACgAJABfACAALQBpAHMAIABbAEQAYQB0AGUAVABpAG0AZQBdACAALQBvAHIAIAAkAF8AIAAtAGkAcwAgAFsAVABpAG0AZQBTAHAAYQBuAF0AKQAgAHsAIAAiACcAJAAoACQAXwApACcAIgAgAH0AIABlAGwAcwBlACAAewAgACQAXwAgAH0AIAB9AAoAIAAgACAAIAAgACAAJABvAGIAagBlAGMAdABGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgACQAXwAuAHAAcwBvAGIAagBlAGMAdAAuAFAAcgBvAHAAZQByAHQAaQBlAHMAIAB8ACAAZgBvAHIAZQBhAGMAaAAgAHsAIAAiACQAKAAkAF8ALgBuAGEAbQBlACkAOgAgACQAKAAmACQAdgBhAGwAdQBlAEYAbwByAG0AYQB0AHQAZQByACAAJABfAC4AdgBhAGwAdQBlACkAIgAgAH0AIAB9AAoACgAgACAAIAAgACAAIAAkAHcAcwB1AHMAIAA9ACAAWwBNAGkAYwByAG8AcwBvAGYAdAAuAFUAcABkAGEAdABlAFMAZQByAHYAaQBjAGUAcwAuAEEAZABtAGkAbgBpAHMAdAByAGEAdABpAG8AbgAuAEEAZABtAGkAbgBQAHIAbwB4AHkAXQA6ADoARwBlAHQAVQBwAGQAYQB0AGUAUwBlAHIAdgBlAHIAKAApAAoAIAAgACAAIAAgACAAJABjAG8AbgBmACAAPQAgACQAdwBzAHUAcwAuAEcAZQB0AEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4AKAApAAoACgAgACAAIAAgACAAIAAjACAARgBpAHIAcwB0ACAAZABvAGMAdQBtAGUAbgB0ACAAaQBzACAAVwBzAHUAcwAgAEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4ACgAgACAAIAAgACAAIAAmACQAbwBiAGoAZQBjAHQARgBvAHIAbQBhAHQAdABlAHIAIAAkAGMAbwBuAGYACgAKACAAIAAgACAAIAAgACMAIABTAGUAYwBvAG4AZAAgAGQAbwBjAHUAbQBlAG4AdAAgAGkAcwAgAHQAaABlACAAbABpAHMAdAAgAG8AZgAgAGUAbgBhAGIAbABlAGQAIABVAHAAZABhAHQAZQAgAGwAYQBuAGcAdQBhAGcAZQBzACAAbwBuACAAYwB1AHIAcgBlAG4AdAAgAHMAZQByAHYAZQByAAoAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcALQAtAC0AJwAKACAAIAAgACAAIAAgACQAYwBvAG4AZgAuAEcAZQB0AEUAbgBhAGIAbABlAGQAVQBwAGQAYQB0AGUATABhAG4AZwB1AGEAZwBlAHMAKAApACAAfAAgAGYAbwByAGUAYQBjAGgAIAB7ACAAJwAtACAAIgAnACAAKwAgACQAXwAgACsAIAAnACIAJwAgAH0ACgAgACAAIAAgAH0ACgA= ----
STDOUT: 
STDERR: The system cannot find the path specified.
---- End output of %windir%/SysNative/WindowsPowershell/v1.0/PowerShell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -InputFormat None -EncodedCommand IAAgACAAIAAkAGEAcwBzAGUAbQBiAGwAeQAgAD0AIABbAFIAZQBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZABXAGkAdABoAFAAYQByAHQAaQBhAGwATgBhAG0AZQAoACcATQBpAGMAcgBvAHMAbwBmAHQALgBVAHAAZABhAHQAZQBTAGUAcgB2AGkAYwBlAHMALgBBAGQAbQBpAG4AaQBzAHQAcgBhAHQAaQBvAG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAYQBzAHMAZQBtAGIAbAB5ACAALQBuAGUAIAAkAG4AdQBsAGwAKQAgAHsACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGIAdQBmAGYAZQByACAAcwBpAHoAZQAgAHQAbwAgAGEAdgBvAGkAZAAgADgAMAAgAGMAbwBsAHUAbQBuACAAbABpAG0AaQB0AGEAdABpAG8AbgAsACAAYQAgAHcAaQBkAHQAaAAgAGcAcgBlAGEAdABlAHIAIAB0AGgAYQBuACAAMQAwADAAMAAgAGkAcwAgAHUAcwBlAGwAZQBzAHMACgAgACAAIAAgACAAIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBCAHUAZgBmAGUAcgBTAGkAegBlACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEgAbwBzAHQALgBTAGkAegBlACgAMQAwADAAMAAsACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AQgB1AGYAZgBlAHIAUwBpAHoAZQAuAEgAZQBpAGcAaAB0ACkACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGkAbgB2AGEAcgBpAGEAbgB0ACAAYwB1AGwAdAB1AHIAZQAgAGYAbwByACAAYwB1AHIAcgBlAG4AdAAgAHMAZQBzAHMAaQBvAG4AIAB0AG8AIABhAHYAbwBpAGQAIABGAGwAbwBhAHQAaQBuAGcAIABwAG8AaQBuAHQAIABjAG8AbgB2AGUAcgBzAGkAbwBuACAAaQBzAHMAdQBlAAoAIAAgACAAIAAgACAAWwBUAGgAcgBlAGEAZABpAG4AZwAuAFQAaAByAGUAYQBkAF0AOgA6AEMAdQByAHIAZQBuAHQAVABoAHIAZQBhAGQALgBDAHUAcgByAGUAbgB0AEMAdQBsAHQAdQByAGUAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEcAbABvAGIAYQBsAGkAegBhAHQAaQBvAG4ALgBDAHUAbAB0AHUAcgBlAEkAbgBmAG8AXQA6ADoASQBuAHYAYQByAGkAYQBuAHQAQwB1AGwAdAB1AHIAZQAKAAoAIAAgACAAIAAgACAAIwAgAEQAZQBmAGkAbgBlAHMAIABzAGkAbgBnAGwAZQAtAGwAZQB2AGUAbAAgACIAWQBBAE0ATAAiACAAZgBvAHIAbQBhAHQAdABlAHIAcwAgAHQAbwAgAGEAdgBvAGkAZAAgAEQAYQB0AGUAVABpAG0AZQAgAGEAbgBkACAAVABpAG0AZQBTAHAAYQBuACAAYwBvAG4AdgBlAHIAcwBpAG8AbgAgAGkAcwBzAHUAZQAgAGkAbgAgAHIAdQBiAHkACgAgACAAIAAgACAAIAAkAHYAYQBsAHUAZQBGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgAGkAZgAgACgAJABfACAALQBpAHMAIABbAEQAYQB0AGUAVABpAG0AZQBdACAALQBvAHIAIAAkAF8AIAAtAGkAcwAgAFsAVABpAG0AZQBTAHAAYQBuAF0AKQAgAHsAIAAiACcAJAAoACQAXwApACcAIgAgAH0AIABlAGwAcwBlACAAewAgACQAXwAgAH0AIAB9AAoAIAAgACAAIAAgACAAJABvAGIAagBlAGMAdABGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgACQAXwAuAHAAcwBvAGIAagBlAGMAdAAuAFAAcgBvAHAAZQByAHQAaQBlAHMAIAB8ACAAZgBvAHIAZQBhAGMAaAAgAHsAIAAiACQAKAAkAF8ALgBuAGEAbQBlACkAOgAgACQAKAAmACQAdgBhAGwAdQBlAEYAbwByAG0AYQB0AHQAZQByACAAJABfAC4AdgBhAGwAdQBlACkAIgAgAH0AIAB9AAoACgAgACAAIAAgACAAIAAkAHcAcwB1AHMAIAA9ACAAWwBNAGkAYwByAG8AcwBvAGYAdAAuAFUAcABkAGEAdABlAFMAZQByAHYAaQBjAGUAcwAuAEEAZABtAGkAbgBpAHMAdAByAGEAdABpAG8AbgAuAEEAZABtAGkAbgBQAHIAbwB4AHkAXQA6ADoARwBlAHQAVQBwAGQAYQB0AGUAUwBlAHIAdgBlAHIAKAApAAoAIAAgACAAIAAgACAAJABjAG8AbgBmACAAPQAgACQAdwBzAHUAcwAuAEcAZQB0AEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4AKAApAAoACgAgACAAIAAgACAAIAAjACAARgBpAHIAcwB0ACAAZABvAGMAdQBtAGUAbgB0ACAAaQBzACAAVwBzAHUAcwAgAEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4ACgAgACAAIAAgACAAIAAmACQAbwBiAGoAZQBjAHQARgBvAHIAbQBhAHQAdABlAHIAIAAkAGMAbwBuAGYACgAKACAAIAAgACAAIAAgACMAIABTAGUAYwBvAG4AZAAgAGQAbwBjAHUAbQBlAG4AdAAgAGkAcwAgAHQAaABlACAAbABpAHMAdAAgAG8AZgAgAGUAbgBhAGIAbABlAGQAIABVAHAAZABhAHQAZQAgAGwAYQBuAGcAdQBhAGcAZQBzACAAbwBuACAAYwB1AHIAcgBlAG4AdAAgAHMAZQByAHYAZQByAAoAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcALQAtAC0AJwAKACAAIAAgACAAIAAgACQAYwBvAG4AZgAuAEcAZQB0AEUAbgBhAGIAbABlAGQAVQBwAGQAYQB0AGUATABhAG4AZwB1AGEAZwBlAHMAKAApACAAfAAgAGYAbwByAGUAYQBjAGgAIAB7ACAAJwAtACAAIgAnACAAKwAgACQAXwAgACsAIAAnACIAJwAgAH0ACgAgACAAIAAgAH0ACgA= ----
Ran %windir%/SysNative/WindowsPowershell/v1.0/PowerShell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -InputFormat None -EncodedCommand IAAgACAAIAAkAGEAcwBzAGUAbQBiAGwAeQAgAD0AIABbAFIAZQBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZABXAGkAdABoAFAAYQByAHQAaQBhAGwATgBhAG0AZQAoACcATQBpAGMAcgBvAHMAbwBmAHQALgBVAHAAZABhAHQAZQBTAGUAcgB2AGkAYwBlAHMALgBBAGQAbQBpAG4AaQBzAHQAcgBhAHQAaQBvAG4AJwApAAoAIAAgACAAIABpAGYAIAAoACQAYQBzAHMAZQBtAGIAbAB5ACAALQBuAGUAIAAkAG4AdQBsAGwAKQAgAHsACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGIAdQBmAGYAZQByACAAcwBpAHoAZQAgAHQAbwAgAGEAdgBvAGkAZAAgADgAMAAgAGMAbwBsAHUAbQBuACAAbABpAG0AaQB0AGEAdABpAG8AbgAsACAAYQAgAHcAaQBkAHQAaAAgAGcAcgBlAGEAdABlAHIAIAB0AGgAYQBuACAAMQAwADAAMAAgAGkAcwAgAHUAcwBlAGwAZQBzAHMACgAgACAAIAAgACAAIAAkAEgAbwBzAHQALgBVAEkALgBSAGEAdwBVAEkALgBCAHUAZgBmAGUAcgBTAGkAegBlACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEgAbwBzAHQALgBTAGkAegBlACgAMQAwADAAMAAsACAAJABIAG8AcwB0AC4AVQBJAC4AUgBhAHcAVQBJAC4AQgB1AGYAZgBlAHIAUwBpAHoAZQAuAEgAZQBpAGcAaAB0ACkACgAgACAAIAAgACAAIAAjACAAUwBlAHQAcwAgAGkAbgB2AGEAcgBpAGEAbgB0ACAAYwB1AGwAdAB1AHIAZQAgAGYAbwByACAAYwB1AHIAcgBlAG4AdAAgAHMAZQBzAHMAaQBvAG4AIAB0AG8AIABhAHYAbwBpAGQAIABGAGwAbwBhAHQAaQBuAGcAIABwAG8AaQBuAHQAIABjAG8AbgB2AGUAcgBzAGkAbwBuACAAaQBzAHMAdQBlAAoAIAAgACAAIAAgACAAWwBUAGgAcgBlAGEAZABpAG4AZwAuAFQAaAByAGUAYQBkAF0AOgA6AEMAdQByAHIAZQBuAHQAVABoAHIAZQBhAGQALgBDAHUAcgByAGUAbgB0AEMAdQBsAHQAdQByAGUAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEcAbABvAGIAYQBsAGkAegBhAHQAaQBvAG4ALgBDAHUAbAB0AHUAcgBlAEkAbgBmAG8AXQA6ADoASQBuAHYAYQByAGkAYQBuAHQAQwB1AGwAdAB1AHIAZQAKAAoAIAAgACAAIAAgACAAIwAgAEQAZQBmAGkAbgBlAHMAIABzAGkAbgBnAGwAZQAtAGwAZQB2AGUAbAAgACIAWQBBAE0ATAAiACAAZgBvAHIAbQBhAHQAdABlAHIAcwAgAHQAbwAgAGEAdgBvAGkAZAAgAEQAYQB0AGUAVABpAG0AZQAgAGEAbgBkACAAVABpAG0AZQBTAHAAYQBuACAAYwBvAG4AdgBlAHIAcwBpAG8AbgAgAGkAcwBzAHUAZQAgAGkAbgAgAHIAdQBiAHkACgAgACAAIAAgACAAIAAkAHYAYQBsAHUAZQBGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgAGkAZgAgACgAJABfACAALQBpAHMAIABbAEQAYQB0AGUAVABpAG0AZQBdACAALQBvAHIAIAAkAF8AIAAtAGkAcwAgAFsAVABpAG0AZQBTAHAAYQBuAF0AKQAgAHsAIAAiACcAJAAoACQAXwApACcAIgAgAH0AIABlAGwAcwBlACAAewAgACQAXwAgAH0AIAB9AAoAIAAgACAAIAAgACAAJABvAGIAagBlAGMAdABGAG8AcgBtAGEAdAB0AGUAcgAgAD0AIAB7ACAAcABhAHIAYQBtACgAJABfACkAOwAgACQAXwAuAHAAcwBvAGIAagBlAGMAdAAuAFAAcgBvAHAAZQByAHQAaQBlAHMAIAB8ACAAZgBvAHIAZQBhAGMAaAAgAHsAIAAiACQAKAAkAF8ALgBuAGEAbQBlACkAOgAgACQAKAAmACQAdgBhAGwAdQBlAEYAbwByAG0AYQB0AHQAZQByACAAJABfAC4AdgBhAGwAdQBlACkAIgAgAH0AIAB9AAoACgAgACAAIAAgACAAIAAkAHcAcwB1AHMAIAA9ACAAWwBNAGkAYwByAG8AcwBvAGYAdAAuAFUAcABkAGEAdABlAFMAZQByAHYAaQBjAGUAcwAuAEEAZABtAGkAbgBpAHMAdAByAGEAdABpAG8AbgAuAEEAZABtAGkAbgBQAHIAbwB4AHkAXQA6ADoARwBlAHQAVQBwAGQAYQB0AGUAUwBlAHIAdgBlAHIAKAApAAoAIAAgACAAIAAgACAAJABjAG8AbgBmACAAPQAgACQAdwBzAHUAcwAuAEcAZQB0AEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4AKAApAAoACgAgACAAIAAgACAAIAAjACAARgBpAHIAcwB0ACAAZABvAGMAdQBtAGUAbgB0ACAAaQBzACAAVwBzAHUAcwAgAEMAbwBuAGYAaQBnAHUAcgBhAHQAaQBvAG4ACgAgACAAIAAgACAAIAAmACQAbwBiAGoAZQBjAHQARgBvAHIAbQBhAHQAdABlAHIAIAAkAGMAbwBuAGYACgAKACAAIAAgACAAIAAgACMAIABTAGUAYwBvAG4AZAAgAGQAbwBjAHUAbQBlAG4AdAAgAGkAcwAgAHQAaABlACAAbABpAHMAdAAgAG8AZgAgAGUAbgBhAGIAbABlAGQAIABVAHAAZABhAHQAZQAgAGwAYQBuAGcAdQBhAGcAZQBzACAAbwBuACAAYwB1AHIAcgBlAG4AdAAgAHMAZQByAHYAZQByAAoAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcALQAtAC0AJwAKACAAIAAgACAAIAAgACQAYwBvAG4AZgAuAEcAZQB0AEUAbgBhAGIAbABlAGQAVQBwAGQAYQB0AGUATABhAG4AZwB1AGEAZwBlAHMAKAApACAAfAAgAGYAbwByAGUAYQBjAGgAIAB7ACAAJwAtACAAIgAnACAAKwAgACQAXwAgACsAIAAnACIAJwAgAH0ACgAgACAAIAAgAH0ACgA= returned 1
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout.rb:289:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout.rb:276:in `error!'
c:/chef/cache/cookbooks/wsus-server/libraries/base_provider.rb:74:in `powershell_out64'
c:/chef/cache/cookbooks/wsus-server/providers/configuration.rb:51:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:667:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:662:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:662:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:701:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:267:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:243:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:226:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:442:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:442:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:426:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:61:in `load'
C:/opscode/chef/bin/chef-client:61:in `<main>'`

**Comment by jdgoins** [comment]
This appears to be a problem when using the latest version of chef-client (12.9.41). It works on 12.8.1.

**Comment by Annih** [comment]
Hello @jdgoins 

Indeed it's due to the fact recent release of chef-client are now running 64bit ruby :)
I don't have a fix for you right now, my wish is to get rid of powershell here - see #12

But I guess I can try to find a workaround.

**Comment by Annih** [comment]
Should be fixed [in v1.0.5](https://supermarket.chef.io/cookbooks/wsus-server/versions/1.0.5)
